= Vinyl Shelf Finder

== About
All original credit to https://github.com/valentingalea/vinyl-shelf-finder ! 
This fork focuses on tweaking the scrobbling interface and removing the (very cool) raspi and laser, resulting in a simple record scrobbler integrating one's Discogs collection and last.fm accounts.

== Features
WIP and very primitive

- web app powered by Node.js
- custom searches in a Discogs collection
- cover art display with optional image caching
- Last.fm integration (as well as local database backup)
- ~~interfaces with a hardware pan-tilt laser pointer~~

== Installation
DISCLAMER: for the brave, no guarantees

=== Node.js

Install https://nodejs.org/en/download/[Node.js] 6.x+

Clone / download this repository; navigate to the `app` folder

`cd app`

Install all the dependencies

`npm install`

=== Setup

Open `app/src/config.js` and edit appropriately with your Discogs.com info.

Optionally - navigate to `app/src` and create the file `last_fm_secret.js` with the contents:

-----
const Secrets = module.exports = { 
    apiKey: "<get this from last.fm>", 
    apiSecret: "<get this from last.fm>",
    username: "<your last.fm account>",
    password: "<your last.fm password>"
};
-----

=== Start

`node app.js`

the `sqlite` database module may not work for all platforms, it can be disabled with

`node app.js --no-db`

the Last.fm integration can be disabled with

`node app.js --no-lastfm`

== Usage

Navigate with any browser to

`http://localhost:8080`

== Documentation

There is a https://valentingalea.github.io/vinyl-shelf-finder/[micro-website] setup via the `docs` folder

